name: TEST N1

on:
  schedule:
    - cron: "0 2 * * 1"  # 每周一 0 点执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  send_email:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Wait for a random time
        run: sleep $(( RANDOM % 600 ))
      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 可根据需要调整为具体的版本

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 使用 requirements.txt 管理依赖

      # Step 4: 运行邮件发送脚本
      - name: Run email sender script
        env:
          EMAIL_CONFIG: ${{ secrets.EMAIL_CONFIG }}
          TG_ID: ${{ secrets.TG_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          python "send_email.py"
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
